import { execSync } from "child_process";
import { cpSync, rmSync, mkdirSync, existsSync, writeFileSync, readFileSync, readdirSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");
const dist = resolve(root, "dist");
const isDev = process.argv.includes("--dev");
const skipObfuscation = process.argv.includes("--no-obfuscate");

console.log(`[fees.fun] Building Chrome Extension (${isDev ? "development" : "production"})...\n`);

// Clean dist — remove built files but keep the directory so Chrome
// doesn't lose the extension identity and wipe chrome.storage.local
if (existsSync(dist)) {
  for (const entry of readdirSync(dist)) {
    rmSync(resolve(dist, entry), { recursive: true });
  }
} else {
  mkdirSync(dist, { recursive: true });
}

// Generate a unique build identifier for this build
const buildId = new Date().toISOString().replace(/[:.]/g, "-");
const buildInfoPath = resolve(root, "src/lib/buildInfo.ts");

writeFileSync(
  buildInfoPath,
  `// Auto-generated by scripts/build.js\n` +
    `// Do not edit manually. Used to show the current build in the popup.\n` +
    `export const BUILD_ID = "${buildId}";\n`
);

console.log(`[fees.fun] Build ID: ${buildId}\n`);

// Generate a random channel key for stealth ISOLATED↔MAIN world communication.
// Changes every build — CustomEvent type is unguessable, AND addEventListener is blocked for it.
const channelKey = Math.random().toString(36).slice(2) + Math.random().toString(36).slice(2);
process.env.VITE_CHANNEL_KEY = channelKey;

function runBuild(target) {
  const modeFlag = isDev ? " --mode development" : "";
  execSync(`npx vite build${modeFlag}`, {
    cwd: root,
    stdio: "inherit",
    env: { ...process.env, BUILD_TARGET: target },
  });
}

// Step 1: Build popup (React app)
console.log("[1/9] Building popup...");
runBuild("popup");

// Step 2: Build background service worker
console.log("\n[2/9] Building background service worker...");
runBuild("background");

// Step 3: Build content script
console.log("\n[3/9] Building content script...");
runBuild("content");

// Step 4: Build shield (MAIN world — anti-detection, must load before interceptors)
console.log("\n[4/9] Building shield...");
runBuild("shield");

// Step 5: Build WS interceptor (MAIN world — self-contained)
console.log("\n[5/9] Building WS interceptor...");
runBuild("ws-interceptor");

// Step 6: Build HTTP interceptor (MAIN world — self-contained)
console.log("\n[6/9] Building HTTP interceptor...");
runBuild("http-interceptor");

// Step 7: Build J7 interceptor (MAIN world — self-contained)
console.log("\n[7/9] Building J7 interceptor...");
runBuild("j7-interceptor");

// Step 8: Build Axiom cache bridge (ISOLATED world — reads cache from chrome.storage)
console.log("\n[8/10] Building Axiom cache bridge...");
runBuild("axiom-cache-bridge");

// Step 9: Build Axiom interceptor (MAIN world — source code patcher)
console.log("\n[9/10] Building Axiom interceptor...");
runBuild("axiom-interceptor");

// Step 10: Copy static assets
console.log("\n[10/10] Copying static assets...");

// Process manifest — strip localhost entries in production builds
const manifest = JSON.parse(readFileSync(resolve(root, "public/manifest.json"), "utf-8"));
if (!isDev && manifest.host_permissions) {
  manifest.host_permissions = manifest.host_permissions.filter(
    (p) => !p.includes("localhost")
  );
}
writeFileSync(resolve(dist, "manifest.json"), JSON.stringify(manifest, null, 2));

// Copy icons if they exist
const iconsDir = resolve(root, "public/icons");
if (existsSync(iconsDir)) {
  cpSync(iconsDir, resolve(dist, "icons"), { recursive: true });
}

// Copy images if they exist
const imagesDir = resolve(root, "public/images");
if (existsSync(imagesDir)) {
  cpSync(imagesDir, resolve(dist, "images"), { recursive: true });
}

// Copy declarativeNetRequest rules if they exist
const rulesDir = resolve(root, "public/rules");
if (existsSync(rulesDir)) {
  cpSync(rulesDir, resolve(dist, "rules"), { recursive: true });
}

// obfuscate inject files in production builds so sites cant just read our source
if (!isDev && !skipObfuscation) {
  const JavaScriptObfuscator = (await import("javascript-obfuscator")).default;
  const API_TOKEN = process.env.JSO_API_TOKEN;
  if (!API_TOKEN) {
    console.error("ERROR: JSO_API_TOKEN env var not set. Skipping obfuscation.");
    console.error("  export JSO_API_TOKEN=\"jso_...\"");
    process.exit(1);
  }

  const filesToObfuscate = [
    "shield.js",
    "ws-interceptor.js",
    "http-interceptor.js",
    "j7-interceptor.js",
    "axiom-interceptor.js",
    "axiom-cache-bridge.js",
    "content.js",
  ];

  // vite builds these as IIFE so all functions are inside the wrapper,
  // none are root-level = function names get fully hidden by VM automatically
  const vmConfig = {
    // vm core
    vmObfuscation: true,
    vmObfuscationThreshold: 1,
    vmPreprocessIdentifiers: true,

    // bytecode hardening - prevents LLM analysis
    vmBytecodeEncoding: true,
    vmBytecodeArrayEncoding: true,
    vmInstructionShuffle: true,
    vmOpcodeShuffle: true,
    vmDecoyOpcodes: true,
    vmDeadCodeInjection: true,

    // anti-debugging
    vmDebugProtection: true,

    // output
    compact: true,
    target: "browser-no-eval", // safest for varying page CSPs
  };

  console.log("\nObfuscating inject files (VM mode)...");
  for (const file of filesToObfuscate) {
    const filePath = resolve(dist, file);
    if (!existsSync(filePath)) continue;
    const code = readFileSync(filePath, "utf-8");
    const result = await JavaScriptObfuscator.obfuscatePro(
      code,
      vmConfig,
      { apiToken: API_TOKEN }
    );
    writeFileSync(filePath, result.getObfuscatedCode());
    console.log(`  obfuscated ${file}`);
  }
}

console.log("\n[fees.fun] Build complete! Extension is in ./dist/");
console.log("Load it in chrome://extensions with Developer mode enabled.");
