import { execSync } from "child_process";
import { cpSync, rmSync, mkdirSync, existsSync, writeFileSync, readFileSync, readdirSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");
const dist = resolve(root, "dist");
const isDev = process.argv.includes("--dev");
const skipObfuscation = process.argv.includes("--no-obfuscate");
const includeAutoUpdater = process.argv.includes("--auto-updater");
const useProdApi = process.argv.includes("--prod-api");

console.log(`[fees.fun] Building Chrome Extension (${isDev ? "development" : "production"}${useProdApi && isDev ? " + prod API" : ""})...\n`);

// Clean dist — remove built files but keep the directory so Chrome
// doesn't lose the extension identity and wipe chrome.storage.local
if (existsSync(dist)) {
  for (const entry of readdirSync(dist)) {
    rmSync(resolve(dist, entry), { recursive: true });
  }
} else {
  mkdirSync(dist, { recursive: true });
}

// Generate a unique build identifier for this build
const buildId = new Date().toISOString().replace(/[:.]/g, "-");
const buildInfoPath = resolve(root, "src/lib/buildInfo.ts");

// Read version from version.json
const versionFile = resolve(root, "version.json");
let extensionVersion = "0.0.0";
if (existsSync(versionFile)) {
  extensionVersion = JSON.parse(readFileSync(versionFile, "utf-8")).version;
}

// Set env vars for Vite (available via import.meta.env)
process.env.VITE_EXTENSION_VERSION = extensionVersion;
if (includeAutoUpdater && !isDev) {
  process.env.VITE_AUTO_UPDATER = "true";
}

// --prod-api: use production URLs while keeping dev mode features (dev menu, IS_DEV, no obfuscation)
if (useProdApi && isDev) {
  process.env.VITE_API_URL = "https://www.fees.fun";
  process.env.VITE_WS_PROXY_URL = "wss://api-eu.fees.fun";
}

writeFileSync(
  buildInfoPath,
  `// Auto-generated by scripts/build.js\n` +
    `// Do not edit manually.\n` +
    `export const BUILD_ID = "${buildId}";\n` +
    `export const VERSION = "${extensionVersion}";\n` +
    `export const AUTO_UPDATER_ENABLED = ${includeAutoUpdater && !isDev};\n`
);

console.log(`[fees.fun] Build ID: ${buildId}`);
console.log(`[fees.fun] Version: ${extensionVersion}`);
if (includeAutoUpdater && !isDev) console.log(`[fees.fun] Auto-updater: ENABLED`);
console.log();

// Generate a random channel key for stealth ISOLATED↔MAIN world communication.
// Changes every build — CustomEvent type is unguessable, AND addEventListener is blocked for it.
const channelKey = Math.random().toString(36).slice(2) + Math.random().toString(36).slice(2);
process.env.VITE_CHANNEL_KEY = channelKey;

function runBuild(target) {
  const modeFlag = isDev ? " --mode development" : "";
  execSync(`npx vite build${modeFlag}`, {
    cwd: root,
    stdio: "inherit",
    env: { ...process.env, BUILD_TARGET: target },
  });
}

// Step 1: Build popup (React app)
console.log("[1/9] Building popup...");
runBuild("popup");

// Step 2: Build background service worker
console.log("\n[2/9] Building background service worker...");
runBuild("background");

// Step 3: Build content script
console.log("\n[3/9] Building content script...");
runBuild("content");

// Step 4: Build Uxento (MAIN world — self-contained)
console.log("\n[4/10] Building Uxento...");
runBuild("uxento");

// Step 5: Build RapidLaunch (MAIN world — self-contained)
console.log("\n[5/10] Building RapidLaunch...");
runBuild("rapidlaunch");

// Step 6: Build J7Tracker (MAIN world — self-contained)
console.log("\n[6/10] Building J7Tracker...");
runBuild("j7tracker");

// Step 7: Build Axiom cache bridge (ISOLATED world — reads cache from chrome.storage)
console.log("\n[7/10] Building Axiom cache bridge...");
runBuild("axiom-cache-bridge");

// Step 8: Build Axiom (MAIN world — source code patcher)
console.log("\n[8/10] Building Axiom...");
runBuild("axiom");

// Step 9: Build Aegis modulepreload strip (MAIN world — prevents duplicate module instances)
console.log("\n[9/10] Building Aegis preload strip...");
runBuild("aegis-preload-strip");

// Step 10: Copy static assets
console.log("\n[10/10] Copying static assets...");

// Process manifest — strip localhost entries in production builds
const manifest = JSON.parse(readFileSync(resolve(root, "public/manifest.json"), "utf-8"));
if (!isDev && manifest.host_permissions) {
  manifest.host_permissions = manifest.host_permissions.filter(
    (p) => !p.includes("localhost")
  );
}

writeFileSync(resolve(dist, "manifest.json"), JSON.stringify(manifest, null, 2));

// Copy icons if they exist
const iconsDir = resolve(root, "public/icons");
if (existsSync(iconsDir)) {
  cpSync(iconsDir, resolve(dist, "icons"), { recursive: true });
}

// Copy images if they exist
const imagesDir = resolve(root, "public/images");
if (existsSync(imagesDir)) {
  cpSync(imagesDir, resolve(dist, "images"), { recursive: true });
}

// Copy declarativeNetRequest rules if they exist
const rulesDir = resolve(root, "public/rules");
if (existsSync(rulesDir)) {
  cpSync(rulesDir, resolve(dist, "rules"), { recursive: true });
}

// obfuscate inject files in production builds so sites cant just read our source
if (!isDev && !skipObfuscation) {
  const API_TOKEN = process.env.JSO_API_TOKEN;
  if (!API_TOKEN) {
    console.warn("WARN: JSO_API_TOKEN not set — skipping obfuscation.");
    console.warn("  Set it or pass --no-obfuscate to silence this.");
  } else {
  const JavaScriptObfuscator = (await import("javascript-obfuscator")).default;

  const filesToObfuscate = [
    "uxento.js",
    "rapidlaunch.js",
    "j7tracker.js",
    "axiom.js",
    "axiom-cache-bridge.js",
    "content.js",
  ];

  // vite builds these as IIFE so all functions are inside the wrapper,
  // none are root-level = function names get fully hidden by VM automatically
  const vmConfig = {
    // vm core
    vmObfuscation: true,
    vmObfuscationThreshold: 1,
    vmPreprocessIdentifiers: true,

    // bytecode hardening - prevents LLM analysis
    vmBytecodeEncoding: true,
    vmBytecodeArrayEncoding: true,
    vmInstructionShuffle: true,
    vmOpcodeShuffle: true,
    vmDecoyOpcodes: true,
    vmDeadCodeInjection: true,

    // anti-debugging
    vmDebugProtection: true,

    // output
    compact: true,
    target: "browser-no-eval", // safest for varying page CSPs
  };

  console.log("\nObfuscating inject files (VM mode)...");
  for (const file of filesToObfuscate) {
    const filePath = resolve(dist, file);
    if (!existsSync(filePath)) continue;
    const code = readFileSync(filePath, "utf-8");
    const result = await JavaScriptObfuscator.obfuscatePro(
      code,
      vmConfig,
      { apiToken: API_TOKEN }
    );
    writeFileSync(filePath, result.getObfuscatedCode());
    console.log(`  obfuscated ${file}`);
  }
  }
}

console.log("\n[fees.fun] Build complete! Extension is in ./dist/");
console.log("Load it in chrome://extensions with Developer mode enabled.");
